pipeline {
    agent any
    stages {
        stage('Build') {
            environment {
                SAPMACHINE_PUBLISH_GITHUB_TOKEN = credentials('github_reshnm')
            }
            agent {
                dockerfile { dir 'docker/ubuntu_16_04_x86_64' }
            }
            steps {
                sh 'env'
            }
            post {
                success {
                    sh 'echo "Hello"
                }
            }
        }
    }
}
